# use this compose to start a test agents cluster.
services:
  agents-cluster:
    image: linda-agent:latest
    restart: always
    environment:
      - 'LINDA_AGENT_CENTRAL_ENDPOINT={{ Agent central endpoint }}'
      - 'LINDA_NODE_ID={{ node id }}'
      - 'LINDA_HB_PERIOD_MS=5000'
    deploy:
      resources:
        limits:
          memory: 512M