FROM ghcr.io/lukaproject/linda/linda-buildbase-image:latest AS builder

WORKDIR /build

COPY . .
RUN cd agent && go mod download
RUN go build -ldflags="-s -w" -o /app/agent agent/main.go

FROM ubuntu:22.04
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai
ENV TZ="Asia/Shanghai"

WORKDIR /app
COPY --from=builder /app/agent /app/agent
CMD ["./agent"]