
services:
  agents-cluster:
    image: linda-agent:latest
    restart: always
    environment:
      - 'LINDA_AGENT_CENTRAL_ENDPOINT=172.17.0.1:5883'
      - 'LINDA_HB_PERIOD_MS=3000'
    deploy:
      resources:
        limits:
          memory: 512M