FROM ghcr.io/lukaproject/linda/linda-buildbase-image:latest AS builder

WORKDIR /build

COPY . .
RUN go build -ldflags="-s -w" -o /app/agentcentral services/agentcentral/main.go

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai
ENV TZ="Asia/Shanghai"

WORKDIR /app
COPY --from=builder /app/agentcentral /app/agentcentral

EXPOSE 5883
CMD ["./agentcentral"]