# use this compose to start a test agentcentral.
services:
  redis:
    image: "bitnami/redis:latest"
    restart: always
    environment:
      - REDIS_PASSWORD=123456
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 1024mb
    ports:
      - "16379:6379"
  agentcentral:
    image: linda-agentcentral:latest
    restart: always
    network_mode: host
    environment:
      - env=debug
    depends_on:
      - redis
      - fileservicefe
    deploy:
      resources:
        limits:
          memory: 1024M
  fileservicefe:
    image: linda-fileservicefe:latest
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 1024M