/*
 * AgentCentral API
 *
 * This is agent central swagger API
 *
 * API version: 0.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApisListFilesReq struct {
	// File's location path in node
	LocationPath string `json:"locationPath,omitempty"`
}
