/*
 * AgentCentral API
 *
 * This is agent central swagger API
 *
 * API version: 0.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApisNodeInfo struct {
	BagName string `json:"bagName,omitempty"`
	MaxRunningTasks int32 `json:"maxRunningTasks,omitempty"`
	NodeId string `json:"nodeId,omitempty"`
}
