/*
 * AgentCentral API
 *
 * This is agent central swagger API
 *
 * API version: 0.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApisFileInfo struct {
	IsDir bool `json:"isDir,omitempty"`
	ModTime int32 `json:"modTime,omitempty"`
	Name string `json:"name,omitempty"`
	Path string `json:"path,omitempty"`
	Size int32 `json:"size,omitempty"`
}
