/*
 * AgentCentral API
 *
 * This is agent central swagger API
 *
 * API version: 0.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApisNodeJoinResp struct {
	ErrorMsg string `json:"errorMsg,omitempty"`
}
