/*
 * AgentCentral API
 *
 * This is agent central swagger API
 *
 * API version: 0.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApisUploadFilesReq struct {
	Files []ApisUploadFilesReqFiles `json:"files,omitempty"`
	// nodes id list which will receive these files.
	Nodes []string `json:"nodes,omitempty"`
}
