/*
 * AgentCentral API
 *
 * This is agent central swagger API
 *
 * API version: 0.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApisFileContent struct {
	Content []int32 `json:"content,omitempty"`
	Files *ApisFileInfo `json:"files,omitempty"`
}
