/*
 * AgentCentral API
 *
 * This is agent central swagger API
 *
 * API version: 0.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApisAddBagResp struct {
	BagDisplayName string `json:"bagDisplayName,omitempty"`
	BagName string `json:"bagName,omitempty"`
	CreateTimeMs int64 `json:"createTimeMs,omitempty"`
	UpdateTimeMs int64 `json:"updateTimeMs,omitempty"`
}
