/*
 * AgentCentral API
 *
 * This is agent central swagger API
 *
 * API version: 0.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApisAddTaskReq struct {
	ScriptPath string `json:"scriptPath,omitempty"`
	TaskDisplayName string `json:"taskDisplayName,omitempty"`
	WorkingDir string `json:"workingDir,omitempty"`
}
