/*
 * AgentCentral API
 *
 * This is agent central swagger API
 *
 * API version: 0.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApisUploadFilesReqFiles struct {
	// the location of file in node
	LocationPath string `json:"locationPath,omitempty"`
	// File's URI
	Uri string `json:"uri,omitempty"`
}
